version: "3.9"

services:
  db:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    container_name: md-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    env_file:
#      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: public.ecr.aws/a5c3k5z0/magical-drones-app:0.0.1 # Replace this with the newest image tag
    ports:
      - "8080:8080"
    container_name: md-backend-app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_started

volumes:
  db-data: