spring:
  profiles:
    active: prod
  application:
    name: magical-drones-webapp
  mvc:
    servlet:
      path: /v1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/magicaldrones_dev
    username: ${MD_DB_USERNAME}
    password: ${MD_DB_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


aws:
  region: us-east-1
  s3:
    bucket: magical-drones
    bucket-test: magical-drones-integration-tests

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
