spring:
  profiles:
    active: prod
  application:
    name: magical-drones-webapp
  mvc:
    servlet:
      path: /v1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${MD_DB_URL}
    username: ${MD_DB_USERNAME}
    password: ${MD_DB_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


aws:
  region: us-east-1
  s3:
    bucket: ${MD_S3_BUCKET}
    bucket-test: ${MD_S3_BUCKET_TEST}


management:
  endpoints:
    web:
      exposure:
        include:
            - health
            - info
  info:
    env:
      enabled: true

info:
  app:
    name: Magical Drones backend service
    description: A backend web service for the Magical Drones project
    version: @project.version@
