spring:
  profiles:
    active: prod
  application:
    name: magical-drones-webapp
  mvc:
    servlet:
      path: /v1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  tomcat:
    connection-timeout: 120000

  datasource:
    url: ${MD_DB_URL}
    username: ${MD_DB_USERNAME}
    password: ${MD_DB_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false


aws:
  region: us-east-1
  s3:
    bucket: ${MD_S3_BUCKET}
    bucket-test: ${MD_S3_BUCKET_TEST}

hugging-face:
  api:
    token: ${MD_HUGGING_FACE}
    inference-endpoints-url: ${MD_HUGGING_FACE_URL}
    serverless-url: https://api-inference.huggingface.co


management:
  endpoints:
    web:
      exposure:
        include:
            - health
            - info
  info:
    env:
      enabled: true

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
